### ISSUE TITLE
Regarding working of the Project

### ISSUE THREAD

**Issue by astha2412** [SHIVENDRA8004/Travel_Companion_Project#1]
I have worked on the same project, and everything was working pretty, but I don't know how it suddenly gets stop, so I got your repo link to check my error and found that your app is also not working correctly, it is also not fetching the data of restaurants of the given location. Kindle help me with my project!

**Comment by shivendra8004** [comment]
It's because you have reached the limit of no. of request to api in a month. So to fix this problem create a new rapid api account and resubscribe the api from new account. Hope it will solve your issue

**Comment by astha2412** [comment]
Ok sure, Thankyou!
Also wanna ask why your app is not working?
